[tool.poetry]
name = "project_basket"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
pydantic = "*"
opencv-python = "*"
ultralytics = "*"
httpx = "<0.28"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.4"
black = "^24.4.0"
isort = "^5.13.2"
pytest = "^8.2.0"
pytest-asyncio = "^0.23.6"
pre-commit = "^3.7.0"
detect-secrets = "^1.4.0"

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]
ignore = ["E501"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
