"""Create initial basketball analytics schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2025-01-08 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_analyses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('video_fps', sa.Float(), nullable=False),
    sa.Column('video_width', sa.Integer(), nullable=False),
    sa.Column('video_height', sa.Integer(), nullable=False),
    sa.Column('video_total_frames', sa.Integer(), nullable=False),
    sa.Column('video_duration_seconds', sa.Float(), nullable=False),
    sa.Column('total_frames_processed', sa.Integer(), nullable=False),
    sa.Column('frames_with_ball_detected', sa.Integer(), nullable=True),
    sa.Column('ball_detection_rate', sa.Float(), nullable=True),
    sa.Column('total_events_detected', sa.Integer(), nullable=True),
    sa.Column('unique_players_tracked', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('game_duration', sa.Float(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=True),
    sa.Column('possession_changes', sa.Integer(), nullable=True),
    sa.Column('frame_by_frame_data', sa.JSON(), nullable=True),
    sa.Column('player_performance', sa.JSON(), nullable=True),
    sa.Column('shot_chart_data', sa.JSON(), nullable=True),
    sa.Column('possession_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('possession_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('previous_player_id', sa.Integer(), nullable=True),
    sa.Column('ball_position_x', sa.Float(), nullable=False),
    sa.Column('ball_position_y', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('shots_attempted', sa.Integer(), nullable=True),
    sa.Column('shots_made', sa.Integer(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('three_point_attempts', sa.Integer(), nullable=True),
    sa.Column('three_point_made', sa.Integer(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('possessions', sa.Integer(), nullable=True),
    sa.Column('total_possession_time', sa.Float(), nullable=True),
    sa.Column('avg_possession_time', sa.Float(), nullable=True),
    sa.Column('distance_covered', sa.Float(), nullable=True),
    sa.Column('time_in_zones', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shot_attempts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('analysis_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('shooter_id', sa.Integer(), nullable=True),
    sa.Column('shot_position_x', sa.Float(), nullable=False),
    sa.Column('shot_position_y', sa.Float(), nullable=False),
    sa.Column('trajectory', sa.JSON(), nullable=True),
    sa.Column('shot_zone', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('made', sa.Boolean(), nullable=True),
    sa.Column('shot_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['video_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot_attempts')
    op.drop_table('player_stats')
    op.drop_table('possession_events')
    op.drop_table('video_analyses')
    # ### end Alembic commands ###