"""Initial database schema

Revision ID: 6e66c660ab88
Revises: 
Create Date: 2025-08-07 21:07:13.725646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e66c660ab88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('frames_processed', sa.Integer(), nullable=True),
    sa.Column('frames_with_ball', sa.Integer(), nullable=True),
    sa.Column('unique_players', sa.Integer(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('visualize', sa.Boolean(), nullable=True),
    sa.Column('save_frames', sa.Boolean(), nullable=True),
    sa.Column('game_statistics', sa.JSON(), nullable=True),
    sa.Column('processing_summary', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_table('frame_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('detections', sa.JSON(), nullable=True),
    sa.Column('tracking_data', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('ball_analysis', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frame_data_id'), 'frame_data', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('shots_attempted', sa.Integer(), nullable=True),
    sa.Column('shots_made', sa.Integer(), nullable=True),
    sa.Column('field_goal_percentage', sa.Float(), nullable=True),
    sa.Column('three_point_attempts', sa.Integer(), nullable=True),
    sa.Column('three_point_made', sa.Integer(), nullable=True),
    sa.Column('three_point_percentage', sa.Float(), nullable=True),
    sa.Column('possessions', sa.Integer(), nullable=True),
    sa.Column('total_possession_time', sa.Float(), nullable=True),
    sa.Column('avg_possession_time', sa.Float(), nullable=True),
    sa.Column('distance_covered', sa.Float(), nullable=True),
    sa.Column('time_in_zones', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('possessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('previous_player_id', sa.Integer(), nullable=True),
    sa.Column('ball_position_x', sa.Float(), nullable=False),
    sa.Column('ball_position_y', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_possessions_id'), 'possessions', ['id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('shooter_id', sa.Integer(), nullable=True),
    sa.Column('shot_position_x', sa.Float(), nullable=False),
    sa.Column('shot_position_y', sa.Float(), nullable=False),
    sa.Column('shot_zone', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('made', sa.Boolean(), nullable=True),
    sa.Column('shot_value', sa.Integer(), nullable=True),
    sa.Column('trajectory', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_id'), 'shots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_possessions_id'), table_name='possessions')
    op.drop_table('possessions')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_frame_data_id'), table_name='frame_data')
    op.drop_table('frame_data')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
